OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
WEBUSB_ENABLE = no
ORYX_ENABLE = no
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAFLAGS += -flto

